### ISSUE TITLE
URL rewrite in .htaccess is not working

### ISSUE THREAD

**Issue by stodge** [friendica/docker#113]
I followed your website for running Friendica using docker-compose at https://hub.docker.com/_/friendica#! - "Base version - apache". My YAML file is:

```
version: '2'

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_USER=friendica
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=friendica
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  app:
    image: friendica
    restart: always
    volumes:
      - friendica:/var/www/html
    ports:
      - "9090:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=friendica
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=friendica
      - FRIENDICA_ADMIN_MAIL=root@friendica.local      
    depends_on:
      - db

volumes:
  db:
  friendica: 

```

When I use docker-compose up -d, I get:

`URL rewrite in .htaccess is not working. Make sure you copied .htaccess-dist to .htaccess.
`

Any suggestions? Thanks
