### ISSUE TITLE
brand new docker friendica:apache -- Url rewrite in .htaccess is not working. Check your server configuration.

### ISSUE THREAD

**Issue by quincy** [friendica/docker#124]
I'm following the instructions [here](https://hub.docker.com/_/friendica) to start Friendica using docker-compose.  Here is a copy of my compose file.

```
version: '3'

services:
  friendica.db:
    image: mariadb
    hostname: friendica.db
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_USER=friendica
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=friendica
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  friendica:
    image: friendica:stable-apache
    hostname: friendica.local
    restart: always
    volumes:
      - friendica:/var/www/html
    ports:
      - "8080:80"
    environment:
      - MYSQL_HOST=friendica.db
      - MYSQL_USER=friendica
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=friendica
      - FRIENDICA_ADMIN_MAIL=root@friendica.local
    depends_on:
      - friendica.db

volumes:
  db:
  friendica:
```

The logs report no errors, but when I try to visit `http://friendica.local:8080/`, I see the System Check page and everything is green except the `URL rewrite is working` test.

> Url rewrite in .htaccess is not working. Make sure you copied .htaccess-dist to .htaccess.
>Error message from Curl while fetching
> http://friendica.local:8080/install/testrewrite
> Failed to connect to friendica.local port 8080: Connection refused

If I visit the `/install/testrewrite` page, from either the docker host or the container, I get the same response:
From docker host:
```
$ curl -I http://friendica.local:8080/install/testrewrite
HTTP/1.1 204 No Content
Date: Sun, 23 Aug 2020 22:20:08 GMT
Server: Apache/2.4.38 (Debian)
X-Powered-By: PHP/7.3.21
X-Account-Management-Status: none
```

From container:
```
root@friendica:/var/www/html# curl -I http://friendica.local/install/testrewrite
HTTP/1.1 204 No Content
Date: Sun, 23 Aug 2020 22:19:46 GMT
Server: Apache/2.4.38 (Debian)
X-Powered-By: PHP/7.3.21
X-Account-Management-Status: none
```

I've also verified that inside the container the `.htaccess` file is identical to the `.htaccess-dist` file.

Can someone please help me understand why I can't get past the system check?
