### ISSUE TITLE
Getting PHP Mail using Outlook or Google SMTP Servers

### ISSUE THREAD

**Issue by ThRPctmylSgltwH** [friendica/docker#156]
I have started Friendica on a Raspberry PI OMV setup using the following Portainer Stack.

```
version: '2'
services:
  db:
    image: yobasystems/alpine-mariadb:10.4.17
    restart: always
    volumes:
      - /srv/dev-disk-by-uuid-edfcb58/Files/AppData/Databases/frendica:/var/lib/mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=root_password
  app:
    image: friendica
    restart: always
    volumes:
      - /srv/dev-disk-by-uuid-edfcb58/Files/AppData/Config/frendica:/var/www/html
    ports:
      - "8095:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
      - FRIENDICA_ADMIN_MAIL=xxx@hotmail.com      
    depends_on:
      - db
volumes:
  db:
    driver: local
  friendica:
    driver: local
```

I then added the addon PHP Mailer SMTP by Marcus Mueller version 0.2. I then created the following config/addon.config.php file to attempt to send email from smtp-mail.outlook.com

```
<?php
return [
        'phpmailer' => [
                // smtp (Boolean)
                // Enables SMTP relaying for outbound emails
                'smtp' => false,

                // smtp_server (String)
                // SMTP server host name
                'smtp_server' => 'smtp-mail.outlook.com',

                // smtp_port (Integer)
                // SMTP server port number
                'smtp_port' => 25,

                // smtp_secure (String)
                // What kind of encryption to use on the SMTP connection.
                // Options: '', 'ssl' or 'tls'.
                'smtp_secure' => 'tls',

                // smtp_port_s (Integer)
                // Secure SMTP server port number
                'smtp_port_s' => 587,

                // smtp_username (String)
                // SMTP server authentication user name
                // Empty string disables authentication
                'smtp_username' => 'xxx@hotmail.com',

                // smtp_password (String)
                // SMTP server authentication password
                // Empty string disables authentication
                'smtp_password' => 'password',

                // smtp_from (String)
                // From address used when using the SMTP server
                // Example: no-reply@example.com
                'smtp_from' => 'xxx@hotmail.com',
        ],
];
```

When trying to setup a new account or reset the password, the docker log file in Portainer has this error.

```
172.22.0.1 - - [04/Jul/2021:14:00:57 +0000] "GET /ping?format=json&_=1625407256755 HTTP/1.1" 200 584 "https://social.domain.com/lostpass" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
msmtp: account default not found: no configuration file available,
msmtp: account default not found: no configuration file available,
172.22.0.1 - - [04/Jul/2021:14:01:01 +0000] "POST /lostpass HTTP/1.1" 302 379 "https://social.domain.com/lostpass" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
```

Can you provide help to get a functioning system?

Thanks

**Comment by nupplaphil** [comment]
so does the smtp sending at least work?

The log entry is because I forgot creating a default setting for MSMTP to deactivate it .. It searches for settings even in case we don't want to ... I'll fix it soon

**Comment by ThRPctmylSgltwH** [comment]
In Portainer, I logged into the console and entered php -a for a php interactive mode.
I then issued the command mail('test@website.com', 'Subject', 'Message');
The same error comes up - msmtp: account default not found: no configuration file available,
So, the email is not sent.
I tried hotmail servers using the configuration above and I also tried gmail servers with the configuration
               'smtp' => false,
               'smtp_server' => 'smtp.gmail.com',
               'smtp_port' => 25,
               'smtp_secure' => 'tls',
               'smtp_port_s' => 587,

Neither sends the email.

If this helps, Friendica gives the error twice in the docker log file in Portainer while the direct command using php interactive mode only lists the error once.

Thanks for looking into this. Once I have a fully functioning system, I will share my configuration so that hopefully others will not have the same issues or the same questions.

**Comment by ThRPctmylSgltwH** [comment]
Hi, do you have any suggestions to get email to work? Without email functioning, I cannot add users. Wouldn't make sense to just offer email configuration in the user interface. This would allow more people to use Friendica that are not so technical savvy? Since it is complicated to have a private email server and avoid it being classified as SPAM, I think that many users would prefer just to use a SMTP server from a large email provider.

**Comment by nupplaphil** [comment]
I' ll take a look tomorrow evening

**Comment by tobiasd** [comment]
Never mind, just saw that you already tried using the phpmailer addon ;-)

**Comment by nupplaphil** [comment]
@ThRPctmylSgltwH 

I would recommend to use the builtin mailserver possibility within the friendica docker image - see https://github.com/friendica/docker#mail-settings

So for your setup, try this as environment variables **instead** of the phpmailer addon:
```yaml
version: '3.2'

services:
  app:
    image: friendica
    restart: always
    hostname: website.com
    volumes:
      - friendica:/var/www/html
    ports:
      - "8080:80"
    environment:
      - [...]
      - SMTP=smtp-mail.outlook.com
      - SMTP_PORT=25
      - SMTP_DOMAIN=hotmail.com
      - SMTP_FROM=xxx
      - SMTP_STARTTLS=true
      - SMTP_AUTH_USER=xx@hotmail.com
      - SMTP_AUTH_PASS=password
```

So as you can see, you don't need an own mailserver :-)
