### ISSUE TITLE
Improve documentation on attaching MySQL database

### ISSUE THREAD

**Issue by Fleker** [friendica/docker#242]
Hey folks,
I am have been working towards setting up a local instance of Friendica and I had hoped the Docker container would be a good way to quickly bootstrap something usable. However, I have found myself stalled amidst several setup issues and I have been having difficulty understanding the documentation.

In particular, I have been able to load the Friendica installer on localhost and get to the DB page. However, I am stuck as I can't seem to connect to my database.
![image](https://github.com/friendica/docker/assets/3291635/c7f8cc58-d43a-4112-aba4-4c6982be6349)

I've created a `docker-compose.yml` which I can start up and it does show both services running and I can access them via Docker. However, they don't seem to talk to each other. I have tried alternatively using MariaDB v MySQL and either way it gives me that error. In addition, I have looked at the logs in both services without spotting any obvious errors.

I'm using a local image to get around #241.

```
version: "2"
# See https://hub.docker.com/_/friendica
services:
  friendica:
    image: friendica-beantown1
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - friendica:/var/www/html
    environment: 
      - MYSQL_HOST=db
      - MYSQL_USER=friendica
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=friendica
  db:
    image: mariadb:latest  # Or mysql:latest
    # image: mysql:latest  # Or mysql:latest
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_USER=friendica
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=friendica
      - MYSQL_RANDOM_ROOT_PASSWORD=no

volumes:
  db: {}
  friendica: {}
```

It'd be great if I'm missing something simple, but efforts to improve the setup docs may generally be helpful.
