### ISSUE TITLE
Adding redis cache to docker-compose

### ISSUE THREAD

**Issue by nupplaphil** [friendica/docker#26]
Since we add redis cache support, I'm going to add a redis cache container in the docker-compose.
like
```yaml
redis:
  image: redis
  restart: always
```
and add the following lines to the `.htconfig.php`:
```php
$a->config['system']['cache_driver'] = 'redis';
$a->config['system']['redis_host'] = 'redis';
$a->config['system']['redis_port'] = 0;
```
