### ISSUE TITLE
2024.09 RC and dev Docker images do not contain Friendica code at all

### ISSUE THREAD

**Issue by Alkarex** [friendica/docker#268]
The Friendica code seems to be gone from recent Docker images:

```console
$ docker run --rm friendica:2024.09-rc-apache ls /usr/src/friendica
config
```

```console
$ docker run --rm friendica:dev ls /usr/src/friendica
config
```

Compare with the latest stable:

```console
$ docker run --rm friendica:apache ls /usr/src/friendica
CHANGELOG
CREDITS.txt
LICENSE
README.md
VERSION
addon
bin
config
database.sql
doc
images
index.php
mod
mods
proxy
security.txt
spec
src
static
update.php
vendor
view
```

Might explain issues like https://github.com/friendica/docker/issues/266#issuecomment-2466431985

**Comment by ne20002** [comment]
The -dev and -rc images download the friendica code upon startup. This is to ensure latest version of branch is used.

**Comment by Alkarex** [comment]
Thanks for the quick answer. That seems like a strange approach (should be a new build, and should be the same than stable to be able to properly test), but anyway, that does not seem to work for me.

```yaml
friendica:
    image: friendica:dev
    container_name: friendica
    hostname: friendica.example.net
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - friendica-data:/var/www/html
    environment:
      - FRIENDICA_ADMIN_MAIL=${ADMIN_EMAIL}
      - FRIENDICA_URL='https://friendica.example.net/'
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=friendica
      - MYSQL_USER=friendica
      - MYSQL_PASSWORD=${MYSQL_FRIENDICA_PASSWORD}
    depends_on:
      - mariadb
 ```

```console
$ docker-compose logs --follow --timestamps --tail 200 friendica
Attaching to friendica
friendica    | 2024-11-17T14:30:33.703170466Z No new Friendica sources found (enable FRIENDICA_UPGRADE for new sources)
friendica    | 2024-11-17T14:30:34.063602084Z [Sun Nov 17 14:30:34.063013 2024] [mpm_prefork:notice] [pid 1:tid 1] AH00163: Apache/2.4.62 (Debian) PHP/8.2.25 configured -- resuming normal operations
friendica    | 2024-11-17T14:30:34.063719101Z [Sun Nov 17 14:30:34.063489 2024] [core:notice] [pid 1:tid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

```console
$ docker exec friendica ls /usr/src/friendica
config
```
