### ISSUE TITLE
Help with `Friendica isn't properly installed yet`

### ISSUE THREAD

**Issue by pilotMike** [friendica/docker#301]
Hello all, I'm trying to get up and running with the docker image of friendica and would appreciate some help. I currently have a server running mutliple apps and use Nginx Proxy Manager to handle ssl and routing.

My understanding is that I really just need the fpm image with the database.

I have the database running in a separate container on an external network called `maria-db-network`. Right now I'm not using Redis, but the idea would be the same.

When the cron container starts, it writes these log messages:
> 2025-03-29 18:39:46.619828+00:00Waiting for MySQL mariadb initialization...
2025-03-29 18:39:46.642016+00:002025-03-29T18:39:46.642016612Z
2025-03-29 18:39:46.645530+00:00Setup MSMTP for 'Michael DiLeo's Friendica' with 'smtp.mailgun.org' ...
2025-03-29 18:39:46.647988+00:00usermod: no changes
2025-03-29 18:39:46.650597+00:00usermod: no changes
2025-03-29 18:39:46.651096+00:00Setup finished
2025-03-29 18:39:46.704710+00:00Friendica isn't properly installed yet.

I have already manually created the user and database for friendica with auth grants:
>+------------------------------------------------------------------------------------------------------------------+
| Grants for friendica@localhost                                                                                   |
+------------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO `friendica`@`localhost` IDENTIFIED BY PASSWORD '*encrypted password here' |
| GRANT ALL PRIVILEGES ON `friendicadb`.* TO `friendica`@`localhost` WITH GRANT OPTION                             |
+------------------------------------------------------------------------------------------------------------------+

I saw somewhere where someone said to grep php -i, so here's that output:
```
# php -i | grep socket
pdo_mysql.default_socket => no value => no value
default_socket_timeout => 60 => 60
```

## Docker yaml for TrueNas Scale
```
services:
  friendica:
    build: /mnt/MainStorage/apps/friendica/config/app
    ports: 
      - "30110:80"
    volumes:
      - /mnt/MainStorage/apps/friendica/data:/var/www/html
      - /mnt/MainStorage/apps/friendica/config/app:/app
    environment:
      - FRIENDICA_ADMIN_MAIL=myemail
      - FRIENDICA_TZ=America/Chicago
      - FRIENDICA_LANG=en
      - FRIENDICA_URL=https://friendica.michaeldileo.org
      - FRIENDICA_SITENAME=Michael DiLeo's Friendica
      - SMTP=mysmtp
      - SMTP_DOMAIN=mydomain
      - SMTP_FROM=admin
      - SMTP_AUTH_USER=admin@mydomain
      - SMTP_AUTH_PASS=lepass
      - SMTP_TLS=true
      - SMTP_STARTTLS=true
      - MYSQL_PASSWORD=facnypass
      - MYSQL_DATABASE=friendica
      - MYSQL_USER=friendica
      - MYSQL_HOST=mariadb
      - MYSQL_PORT=3306
    networks:
      - maria-db-network

  cron:
    build: /mnt/MainStorage/apps/friendica/config/app
    restart: always
    volumes:
      - /mnt/MainStorage/apps/friendica/data:/var/www/html
      - /mnt/MainStorage/apps/friendica/config/app:/app
    entrypoint: /cron.sh
    environment:
      - FRIENDICA_ADMIN_MAIL=myemail
      - FRIENDICA_TZ=America/Chicago
      - FRIENDICA_LANG=en
      - FRIENDICA_URL=https://friendica.michaeldileo.org
      - FRIENDICA_SITENAME=Michael DiLeo's Friendica
      - SMTP=mysmtp
      - SMTP_DOMAIN=mydomain
      - SMTP_FROM=admin
      - SMTP_AUTH_USER=admin@mydomain
      - SMTP_AUTH_PASS=lepass
      - SMTP_TLS=true
      - SMTP_STARTTLS=true
      - MYSQL_PASSWORD=facnypass
      - MYSQL_DATABASE=friendica
      - MYSQL_USER=friendica
      - MYSQL_HOST=mariadb
      - MYSQL_PORT=3306
    depends_on:
      - friendica
    networks:
      - maria-db-network

networks:
  maria-db-network:
    external: true
```
