### ISSUE TITLE
Page not found on startup with frior system theme

### ISSUE THREAD

**Issue by Zauberstuhl** [friendica/docker#36]
On the startup page a "Page Not Found" is displayed and it seams that `mod/home.php` is missing in the image. Is this a bug or do we have a incomplete configuration?

You can see the problem in action here: https://friendica.feneas.org/
and our compose file looks like this:
```
version: '2'
volumes:
  friendica: {}
  db: {}
services:
  app:
    image: friendica/server
    hostname: friendica.local
    environment:
      FRIENDICA_ADMIN_MAIL: hq@feneas.org
      MYSQL_DATABASE: friendica
      MYSQL_HOST: db
      MYSQL_PASSWORD: secret
      MYSQL_USER: friendica
      SMTP: smtphost
      SMTP_AUTH_PASS: smtpuser
      SMTP_AUTH_USER: secret
      SMTP_TLS: '1'
      SITENAME: friendica.feneas.org
    volumes:
    - friendica:/var/www/html
    labels:
      io.rancher.scheduler.affinity:host_label: feneas.host=hel1-3
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: friendica
      MYSQL_PASSWORD: secret
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: friendica
    volumes:
    - db:/var/lib/mysql
    labels:
      io.rancher.scheduler.affinity:host_label: feneas.host=hel1-3
```

Any advice? Thanks in advantage, Lukas
