### ISSUE TITLE
Cannot start service web: OCI runtime create failed

### ISSUE THREAD

**Issue by jaltek** [friendica/docker#8]
By using the docker-compose example for "Base version - FPM" I got an error while firing up the containers:

`ERROR: for friendica_web_1  Cannot start service web: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/srv/docker/friendica/nginx.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/***UUID***/merged\\\" at \\\"/var/lib/docker/overlay2/***UUID***/merged/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

docker-compose created an empty folder ```nginx.conf``` inside the directory of the docker-compose.yml file during startup.

**Comment by nupplaphil** [comment]
Did you create a local `nginx.conf` before starting?

**Comment by jaltek** [comment]
No (I figured that's where the mistake was). If this is a prerequisite maybe it should be mentioned in the README :)

**Comment by nupplaphil** [comment]
Hm.. There is a sentence about looking for examples in the examples folder.

But I will write it more clear / prominent :-)

**Comment by jaltek** [comment]
Well - I first assumed it will run out of the box like the apache example without any further configuration.
A docker compose example YAML file tempts you to try it out quickly :)

**Comment by jaltek** [comment]
If you are going to edit the README because of the nginx-fpm example maybe you should replace the 
```
links:
      - app
```
flag in flavor of version 3 of the compose file.
Quote:

> The --link flag is a legacy feature of Docker. It may eventually be removed. Unless you absolutely need to continue using it, we recommend that you use user-defined networks to facilitate communication between two containers instead of using --link. One feature that user-defined networks do not support that you can do with --link is sharing environmental variables between containers. However, you can use other mechanisms such as volumes to share environment variables between containers in a more controlled way.

Ref: https://docs.docker.com/compose/compose-file/#links

Maybe something like:


```yaml
version: '3'

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_USER=friendica
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=friendica
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      main:
        aliases:
          - db

  app:
    image: friendica/server:fpm
    restart: always
    volumes:
      - friendica:/var/www/html    
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=friendica
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=friendica
      - MAILNAME=root@friendica.local
    hostname: friendica.local
    depends_on:
      - db
    networks:
      main:
        aliases:
          - app

  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
    restart: always
    networks:
      main:
        aliases:
          - web

volumes:
  db:
  friendica:

networks:
  main:
```
