### ISSUE TITLE
External users can't follow me

### ISSUE THREAD

**Issue by commagray** [friendica/docker#99]
Hi!

I have following configuration with Docker, Traefik and Caddy:

docker-compose.yml

```
services:
  db:
    image: mariadb
    restart: always
    volumes:
      - /srv/containers/databases/friendica/mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=[REDACTED]
      - MYSQL_PASSWORD=[REDACTED]
      - MYSQL_DATABASE=[REDACTED]
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      - internal
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=true

  derpapp:
    image: friendica/server
    restart: always
    volumes:
      - /srv/containers/data/friendica:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=[REDACTED]
      - MYSQL_PASSWORD=[REDACTED]
      - MYSQL_DATABASE=[REDACTED]
      - FRIENDICA_ADMIN_MAIL=[REDACTED]
    hostname: derpy.email
    depends_on:
      - db
    networks:
      - internal
      - proxy
    labels:
      - traefik.enable=true
      - traefik.backend=derpapp
      - traefik.docker.network=proxy
      - traefik.port=80
      - traefik.frontend.rule=Host:derpy.email
      - com.centurylinklabs.watchtower.enable=true

networks:
  proxy:
    external: true
  internal:
    external: false
```

derpy.email.conf Caddyfile

```
derpy.email {
        proxy / http://localhost:8080 {
                transparent
        }
        tls [REDACTED] {
                dns cloudflare
        }
        gzip
}
```

Federation seems working (I can ping my Mastodon account and back, faves work too). But Mastodon can't follow  Friendica account:

![image](https://user-images.githubusercontent.com/27947961/71778107-fe46ef80-2fb1-11ea-889a-e7521e1c3b73.png)

And a comment from a libranet.de user:

> The network type couldn't be detected. Contact can't be added.

The only visible problem is https://github.com/friendica/docker/issues/79#issuecomment-570894263
